name: Context example
on: [push]
jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "Step 1"
              run: echo 'Hello! ${{ github.repository_owner }}'
            - name: "Step 2"
              run: echo "Hello again! $MY_ACTION"
              env:
                MY_ACTION: ${{ github.action }}