name: Run Bash Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the script
        run: |
          chmod u+x ./myscript.sh
          ./myscript.sh